apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reminder
  namespace: project
spec:  
  schedule: "0 8 * * *"
  jobTemplate:  
    spec:
      template:
        spec:
          containers:
          - name: reminder
            image: pimpbot9000/reminder:1.01
          restartPolicy: OnFailure