FROM python:latest
WORKDIR /usr/src/app
RUN mkdir static
RUN mkdir templates
COPY app2.py .
COPY requirements.txt .
COPY templates/index.html /usr/src/app/templates/index.html
RUN pip install -r requirements.txt
EXPOSE 8080
ENTRYPOINT [ "python3", "-u", "app2.py" ]
CMD ["static"]

# docker build -t pimpbot9000/app1-12:latest -f Dockerfile.app2 .