FROM ubuntu:latest
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y python3 && apt-get install -y curl
RUN apt-get install -y python3-pip
RUN mkdir static
RUN mkdir templates
COPY app2.py .
COPY requirements.txt .
COPY templates/index.html /usr/src/app/templates/index.html
RUN pip3 install -r requirements.txt
EXPOSE 7070
ENTRYPOINT [ "python3", "-u", "app2.py" ]
CMD ["static"]

# docker build -t pimpbot9000/app1-13:latest -f Dockerfile.app2 .