apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssh-nuke-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ssh-nuke-service
          servicePort: 2345