apiVersion: v1
kind: Service
metadata:
  name: backend-service-internal
spec:
  type: ClusterIP
  selector:
    app: app2-pong2-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5050