FROM python:latest
WORKDIR /usr/src/app
RUN mkdir files
COPY app2.py .
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 8080
ENTRYPOINT [ "python3", "-u", "app2.py" ]
CMD ["file.txt"]


# docker build -t pimpbot9000/app2:latest -f Dockerfile.app2 .