FROM ubuntu:18.04
RUN apt update && apt install -y python3 && apt install -y python3-pip && apt install -y net-tools
WORKDIR /usr/app
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY app.py .
EXPOSE 8080
CMD ["python3", "-u", "app.py"]

# docker build -t ssh-nuke-app:ubuntu -f Dockerfile.ubuntu .