# This is the service for ingress (to outside)

apiVersion: v1
kind: Service
metadata:
  name: pong2-service
spec:
  type: ClusterIP
  selector:
    app: app2-pong2-pod # This is the app as declared in the deployment.
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 6060