apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-pong2-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-pong2-pod
  template:
    metadata:
      labels:
        app: app2-pong2-pod
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim            
      containers:
        - name: app2
          image: pimpbot9000/app2-01:latest
          args: ["/usr/src/app/static", "http://counter-service/counter"]
          #envFrom:
          #- secretRef:
          #    name: my-secrets

          env:
          - name: BACKEND_URL
            value: "http://backend-service-internal/todos"
          - name: MESSAGE                                     
            valueFrom:
              configMapKeyRef:
                name: dotenv
                key: message

          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/static

        - name: pong2
          image: pimpbot9000/pong:2.07
          envFrom:
          - secretRef:
              name: my-secrets
          env:          
          - name: POSTGRES_USER                                     
            valueFrom:
              configMapKeyRef:
                name: dotenv
                key: POSTGRES_USER
          - name: POSTGRES_DB                                     
            valueFrom:
              configMapKeyRef:
                name: dotenv
                key: POSTGRES_DB
          - name: POSTGRES_SERVICE
            value: "postgres-svc"
          - name: POSTGRES_PORT
            value: "5432"

          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/static

        - name: memory-db
          image: pimpbot9000/memory-backend:latest
          args: ["5050"]
          envFrom:
          - secretRef:
              name: my-secrets
          env:                              
          #- name: POSTGRES_PASSWORD                                     
          #  valueFrom:
          #    configMapKeyRef:
          #      name: dotenv
          #      key: POSTGRES_PASSWORD
          - name: POSTGRES_USER                                     
            valueFrom:
              configMapKeyRef:
                name: dotenv
                key: POSTGRES_USER
          - name: POSTGRES_DB                                     
            valueFrom:
              configMapKeyRef:
                name: dotenv
                key: POSTGRES_DB
          - name: POSTGRES_SERVICE
            value: "postgres-svc"
          - name: POSTGRES_PORT
            value: "5432"

