apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-pong2-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2-pong2-pod
  template:
    metadata:
      labels:
        app: app2-pong2-pod
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: app2
          image: pimpbot9000/app1-12:latest
          args: ["/usr/src/app/static"]
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/static
        - name: pong2
          image: pimpbot9000/pong1-12:latest
          args: ["/usr/src/app/static/file.txt"]
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/static